project:
  type: book

book:
  title: "कविता संग्रह"
  author: "बिक्रम अधिकारी"
  date: "04/05/2024"
  chapters:
    - index.qmd
    - Poem1.qmd
    - Poem2.qmd
    - Poem3.qmd
    - Poem4.qmd
    - Poem5.qmd
    - Poem6.qmd
    - Poem7.qmd
    - Poem8.qmd
    - Poem9.qmd
    - Poem10.qmd

page-navigation: true

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

