# मृगतृष्णा

कति त्यहि कापीमा मात्र लेख्ने ।  मेटौदई लेख्दै गरेको नि २ महिना भयो । अरुहरुको भने कापी सक्केपछी राम्रो नँया कापीमा लेख्छन।  म भने सधै थोत्रो तेही पनि हजार पल्ट मेटेर लेख्नु पर्ने । बा आमाले नि कसरि किन्दिउन।  बिहान बेलुका खान त मुस्किल छ । धन्न गर्नु भाको छ । दिन रात मेहेनत गरेर मलाई बिद्यालय त पठाउनु भाको छ।  म त भाग्यमनि हु । पढ्न पाको छु । अनि जस्तोमा लेखेर पढे पनि मुख्य कुरा ज्ञान पाउनु त होनी ।

 कति गाह्रो छ बा लाई । म कसरि माग्ने होला कापी किन्ने पैसा । जस्तै भए पनि माग्नु त परि हाल्यो  नत्र कसरि गृहकार्य गर्ने ।  गृहकार्य  नगरे राम सरले मार्नु हुन्छ ।"

४ बजेको घन्टी लाग्छ । सबै बच्च्चाहरु घर तिर हानिन्छन । तेस्तैमा प्रकाश पनि आफ्नो घर तिर हिड्छ ।

उकालो बाटो । बिधालय बाट घर पुग्न ठ्याक्क २ घण्टा लग्छ । त्यति लामो बाटो खाली पेट हिड्न कति गारो हुन्छ । खाली पेट हिड्न बाध्य तुल्याउने त्यहि गरिबी हो  । गरिब भएर हिड्दा जीवनको पाईला पाईलामा गारो हुन्छ । जीवनको गोरेटो बाटोमा गरिबीले अन्तिम थोपा नझारे सम्म निचोरी रहन्छ । गरिबीको भुमरी बाट निस्किने उपाय एक मात्र हो बिद्या ।  

प्रकाश मनमा अनकौं  कुराहरु मनमा खेलाउदै बिद्यालय बाट आफ्नो घर तिर लग्छ । घर आधा घण्टा बाकी हुदा प्रकाश आफ्नो भोक  मेटाउन बाटोको छ्येउमा रहेको ढुंगे धारामा जान्छ र दिउसभरिको भोक त्यो चिसो पानिले मेटाउछ । पानी पिएर फेरी हिड्न भनेर लाग्दा, बाटोको पल्लो छ्येउमा एउटा अनौठो प्रकारको राम्रो झोला भेट्छ।

"कोहि छन् कि ? कसैले पानि खान जादा बिर्सेको हो कि ?  कसले बिर्स्यो  होला यस्तो राम्रो झोला ? 

म के गरुँ ? होस् अर्का को समान किन चलाउने।  म त घर जान्छु।"

 त्यो झोला उसले नहेरी घर तिर लाग्छ । उसले आफ्नो हिडाइको बेग बडाउछ । उसलाई कति खेर गएर पेटमा करईरहेको मुसा लाई शान्त पार्ने भई राखेको थियो । 

उसले ध्यान दिएको थिएन । उसको आगाडी दुइ जना मान्छे थिए । एउटा आफ्नै बुबाको जस्तो उमेरको अनि अर्को आफ्नै उमेरको बच्चा । उसले आफ्नै घर तिर जना लागेका ति मान्छे हरुलाई चिन्न बडो कोसिस गरि रहेको थियो तर चिन्न सकेको थिएन । प्रकाशले निगालेर  हेर्दा  त्यो बच्चाले उसले उता धारा नेर देखेको जस्तै झोला बोकेको थियो ।  

उसलाई लग्यो कि त्यो झोला उनीहरुले बिर्सेको हुनुपर्छ । उसले उनिहरुलाई भेट्न आफ्नो बेग बडाउछ । जति बेगले हिने पनि उसले भेट्टाउनै सक्दैन । येतिकैमा ति मान्छे हरु ओझेल पर्छन । 

आज जति हिने पनि किन  आफ्नो  घर नआएको होला । एकछिन आराम गर्न ढुंगामा बस्छ । अनि येसो पछाडी हेर्छ।  त्यो झोला उसकै पछाडी हुन्छ । अनि ति मान्छे हरु तलतिर झरेको देख्छ । 

" होइन के भैराको छ । को हुन् तिनीहरु । के  छ यो झोलामा ?" 

झोला खोलेर हेर्छ । उसले देख्छ ठुला ठुला आफुले सोचेको जस्तै राम्रा ठुला कपिहरु । किताब हरु ।  अनि कलम हरु 

आज म यो झोला यतै लुकाएर जान्छु। येदि कसैले आफ्नो झोला खोजे दिन्छु नत्र म आफै राख्छु । त्यो झोला उसले तेही ढुंगाको तल्लो पट्टि लुकाउछ । अनि घर तिर लग्दछ ।

घरमा पुगेर उसले आमाले बनाई राखेको खाना खान्छ । ओछ्यानमा गएर पल्टिन्छ । 

"हे भगवान त्यो झोला लिन कोहि पनि नआओस । येदि कसैले पनि त्यो झोला खोज्न आएन भने मलाई यो बर्ष भरि पढ्न सजिलो हुन्छ । मेटाई मेटाई लेख्नु पर्दैन।  कापी नभएर सरको गाली अनि कुटाई खानु पर्दैन । अनि कपि कलम को लागि बाबा संग पैसा माग्नु पर्दैन । हे भगवान त्यो झोला लिन कोहि पनि नआओस । "

आमा: "छोरा उठ उठ । कति ढिला सम्म सुतेको ।"

प्रकाश : " कति गारो भाको छ । एकछिन सुत्छु ।" एक्कासी हिजो लुकाएको झोला सम्झिन्छ ।  "म त्यहि तल गएर आइहाल्छु भन्दै  तल झोला लुकाएको ठाउँ तिर बेगले कुद्दै जान्छ। "

उसले आमाले भनेको  सुन्यो या सुनेन-  आमा भन्दै थिईन, " आज आइतबार हो बाबु । स्कूल जन ढिला होला "
